name: Main Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Cache
      uses: actions/cache@v4.0.1
      with: 
        # A list of files, directories, and wildcard patterns to cache and restore
        path: 'target/'
        # An explicit key for restoring and saving the cache
        key: 'recorder-rs-build'
      # An optional boolean when enabled, allows windows runners to save or restore caches that can be restored or saved respectively on other platforms
      # Check if a cache entry exists for the given input(s) (key, restore-keys) without downloading the cache
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
